server.port=8083
spring.application.name=call-history-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/callhistorydb}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgrespassword}

spring.jpa.database-platform=${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

search-history-service.url=${SEARCH_HISTORY_SERVICE_URL:http://localhost:8084}

# Actuator Configuration (Seul /actuator/health est exposé)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
