server.port=8084
spring.application.name=search-history-service

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/searchhistorydb}
spring.datasource.driverClassName=${SPRING_DATASOURCE_DRIVER:org.postgresql.Driver}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgrespassword}

spring.jpa.database-platform=${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Clé secrète JWT partagée
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

# Actuator Configuration (Seul /actuator/health est exposé)
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
